import { Project } from 'src/app/models/project';

export const projects: Project[] = [
  {
    "id": 0,
    "name": "UNO",
    "description": "A recreation of UNO using Python, once with a GUI and one using the Console, Both are customizable, the one with the GUI can add a lot of cards using json.",
    "link": "https://github.com/oldmartijntje/UNO",
    "status": "Completed",
    "version": "2.4.0",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/uno.png",
    "creators": "OldMartijntje",
    "readmeUrl": "https://github.com/oldmartijntje/UNO/blob/main/README.md",
    "userFriendlyness": "user friendly unless you try to implement your own things, then it's not user friendly.",
    "customizebility": "You add your own cards, you can say how many you want, you can define every card as in: are they special like a + card or a reverse etc.",
    "scale": "B"
  },
  {
    "id": 1,
    "name": "Pokemon Vibranium",
    "description": "This is a pokemon game made by OldMartijntje using rpg maker xp and using pokemon essentials, It takes place in a new region.",
    "link": "https://github.com/oldmartijntje/Pokemon-Vibranium",
    "status": "~10% | on halt",
    "version": "quadralpha 2.4",
    "type": "rpg maker xp + pokemon essentials",
    "tumbnail": "assets/images/appTextures/pokemonVibranium.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "fully user friendly.",
    "customizebility": "It's not customizable since it's a pokemon game.",
    "scale": "A"
  },
  {
    "id": 2,
    "name": "Project viewer",
    "description": "An angular web-app with sql server to load all my projects, it also works without the sql server",
    "link": "https://github.com/oldmartijntje/Project-Viewer",
    "status": "",
    "version": "",
    "type": "Angular, C#",
    "tumbnail": "assets/images/appTextures/viewer.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": "C"
  },
  {
    "id": 3,
    "name": "Accounts System",
    "description": "A Python account system that saves accounts to json, with the account system you can read data from other apps that use this account system, and your playtime gets stored",
    "link": "https://github.com/oldmartijntje/accounts-system",
    "status": "Completed | Upgradable",
    "version": "v2.8.0",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/account.png",
    "creators": "OldMartijntje",
    "readmeUrl": "https://github.com/oldmartijntje/accounts-system/blob/main/README.md",
    "userFriendlyness": "client friendly if implemented correctly. It's not that difficult to implement as described in the readme and examples folder.",
    "customizebility": "You can intergrate it in multiple ways, as explained in the readme as well as in the examples folder.",
    "scale": "B"
  },
  {
    "id": 4,
    "name": "stonks",
    "description": "a 'game' where you buy stocks, sell them, and hope you don't go bankrupt. only console, sometimes it's really scuffed.",
    "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/simulation/stonks.py",
    "status": "Completed",
    "version": "",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/stonks.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "user friendly, it's explained well",
    "customizebility": "",
    "scale": "D"
  },
  {
    "id": 5,
    "name": "CodeDungeon",
    "description": "This Project is there as learning tool, a tool to teach kids the logic of programming in a fun way, By programming the movement of your character in a game.",
    "link": "https://github.com/oldmartijntje/CodeDungeon",
    "status": "Completed",
    "version": "v1.1.0",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/codeDungeon.png",
    "creators": "OldMartijntje",
    "readmeUrl": "https://github.com/oldmartijntje/CodeDungeon/blob/main/README.md",
    "userFriendlyness": "very user friendly, there is a massive readme that explains everything.",
    "customizebility": "You can change almost everything, add almost everything, very customizable. everything is explained in my readme.",
    "scale": "S"
  },
  {
    "id": 6,
    "name": "LAN-testing",
    "description": "Me testing how lan works, i was going to implement it into uno, but not yet. It's a LAN chat, console version and Tkinter version.",
    "link": "https://github.com/oldmartijntje/LAN-testing",
    "status": "Completed",
    "version": "V0.3.0",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/lan.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "pretty straight forward. Unless you don't know what an IP adress is.",
    "customizebility": "I mean you can implement it in a lot, if you know a bit of coding.",
    "scale": "C"
  },
  {
    "id": 7,
    "name": "pokemarjin",
    "description": "i was going to make a Pokemon game.",
    "link": "https://github.com/oldmartijntje/pokemarjin",
    "status": "Cancelled",
    "version": "",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/pokemarjin.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 8,
    "name": "Betacraft",
    "description": "Minecraft world using the betacraft launcher where i update the world every time i open the world",
    "link": "https://betacraft.uk/",
    "status": "Paused",
    "version": "b1.7.3",
    "type": "BetaCraft Minecraft",
    "tumbnail": "assets/images/appTextures/betacraft.png",
    "creators": "OldMartijntje",
    "readmeUrl": "https://youtu.be/LAXe4MJEs-o",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": "B"
  },
  {
    "id": 9,
    "name": "Reliving -The game",
    "description": "This is a story game i guess, you get options about what to do and you can choose, can you find all the achievements? if you have a file named DLC.activ in the main folder (doesn't matter if it contains data) (you can find one in the DLC/ folder) You have an extra branch to the game, with more achievements, but it's not finished.",
    "link": "https://github.com/oldmartijntje/The-Game",
    "status": "DLC: Cancelled | Original game: Completed",
    "version": "Release 3.2",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/reliving.png",
    "creators": "OldMartijntje",
    "readmeUrl": "https://github.com/oldmartijntje/The-Game/blob/master/README.md",
    "userFriendlyness": "Pretty self explanetory, and the readme helps",
    "customizebility": "some settings in the readme",
    "scale": "D"
  },
  {
    "id": 10,
    "name": "Isis's idee.nds",
    "description": "A mario bros ds hack where i got ideas for levels from my friend. every level started from a hub where 1 diff pipe is opened to start the level.",
    "link": "",
    "status": "Cancelled",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/isisIdee.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 11,
    "name": "texturepackremovalform",
    "description": "Ever had a texture pack u liked in minecraft, but u hated that 1 texture? exactly, i did. so i made this, now you only need to fill in in a txt which textures u hate, and every time when it updates, you can delete those annoying textures. (if it still works) (you need all the files in that folder in the link, but not the whole reposetory) once u downloaded it, head to: texturepackremovalform/bin/Debug/net5.0-windows/texturepackremovalform.exe to activate it.",
    "link": "https://github.com/oldmartijntje/projects/tree/main/csharp/repos/texturepackremovalform",
    "status": "Completed",
    "version": "V1.4",
    "type": "C#",
    "tumbnail": "assets/images/appTextures/texturepackremoval.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "Yeah it's explained quite well, i think?",
    "customizebility": "",
    "scale": "OG"
  },
  {
    "id": 12,
    "name": "Marjin pack",
    "description": "A modpack for minecraft made of random mods",
    "link": "",
    "status": "",
    "version": "V2",
    "type": "file explorer / curseforge",
    "tumbnail": "assets/images/appTextures/marjinpack.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 13,
    "name": "City Build",
    "description": "It's a city in minecraft, well atleast the start",
    "link": "",
    "status": "Cancelled",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/cityBuild.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 14,
    "name": "Prison Discord Server + Bot",
    "description": "A prison server where a bot controls in what call you are, you can move between cells and stuff",
    "link": "",
    "status": "Not really started",
    "version": "",
    "type": "Discord",
    "tumbnail": "assets/images/appTextures/prisonBleuprint.png",
    "creators": "OldMartijntje, Tomsom999",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 15,
    "name": "Big Maze",
    "description": "It's a big maze",
    "link": "",
    "status": "Too lazy",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/bigMaze.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 16,
    "name": "Hard Shit.nds",
    "description": "A kaizo mario bros ds hack which is only one level",
    "link": "",
    "status": "Completed",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/hardShit.png",
    "creators": "Someone on discord",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 17,
    "name": "Piston Maze",
    "description": "t's a really annoying maze",
    "link": "",
    "status": "Complete",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/pistonMaze.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 18,
    "name": "nakijk formulier",
    "description": "This is a program that fills in a form that i had to fill in every time for school and i didn't want to do that every time, so i automated it.",
    "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/nakijk%20formulier/nakijk.py",
    "status": "",
    "version": "",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/nakijk.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "client friendly, just do what it says",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 19,
    "name": "phone",
    "description": "a random calculator that just says you are 10% dumb or something which is randomized. the reason why it's called phone is because i probably made it on my phone.",
    "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/simulation/phone.py",
    "status": "Completed?",
    "version": "",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/phone.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "user friendly, but u only need to fill in a name, that's all",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 20,
    "name": "Golf",
    "description": "Golf coarse in minecraft",
    "link": "",
    "status": "Cancelled",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/golf.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 21,
    "name": "Broken Realms",
    "description": "A minecraft server",
    "link": "",
    "status": "Cancelled (forever)",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/brokenRealms.png",
    "creators": "OldMartijntje, Tomsom999, MellodieMoon, Dejack13",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 22,
    "name": "Minecraft Town",
    "description": "A town in Minecraft where you can play, and with lore.",
    "link": "",
    "status": "Not even started and already Cancelled",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/minecraftTown.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 23,
    "name": "Animation maker",
    "description": "An animation maker",
    "link": "https://scratch.mit.edu/projects/436600255/",
    "status": "Cancelled",
    "version": "",
    "type": "Scratch",
    "tumbnail": "assets/images/appTextures/animationMaker.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 24,
    "name": "good.nds",
    "description": "An 'openworld' mario bros ds hack where every level starts where the last one ended",
    "link": "",
    "status": "Cancelled",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/good.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 25,
    "name": "official nsmb, but switchable tilesets.nds",
    "description": "A new super mario bros ds hack with the original levels, but the tilesets match so it's easy to switch enviroment",
    "link": "",
    "status": "Cancelled",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/tileset.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 26,
    "name": "Project.nds",
    "description": "A mod where different world are meant for different types of people",
    "link": "",
    "status": "Cancelled",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/project.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 27,
    "name": "test.nds",
    "description": "Me testing if you can do a shelljump in new super mario bros ds with a edited level to test it",
    "link": "",
    "status": "Completed",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/test.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 28,
    "name": "watar.nds",
    "description": "I flooded every mario bros ds level, unless it's a water level, then i drained it",
    "link": "",
    "status": "Completed",
    "version": "",
    "type": "NSMB Editor",
    "tumbnail": "assets/images/appTextures/watar.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 29,
    "name": "book",
    "description": "this program generates a give command for minecraft with a randomized story. you can add more things (sentances and stuff) in the json file. how 2 add + how it works: it takes 1 string from the intros dictionary, once it encounters a word with || around it, like this: ||item|| it will take a string from the items dictionary and it will reread the string, until it doesn't encounter a word with || around it anymore. (same thing works with author and name, tho those can't contain spaces, be aware) as title it will pick from ||titles|| and as author it will pick from ||authors|| (authors doesn't exist in the json, it is generated once the script is running by merging some ||people|| with ||newspaper||)",
    "link": "https://github.com/oldmartijntje/projects/blob/main/minecraft/book.py",
    "status": "",
    "version": "",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/book.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "You can add as many words and centances as you wish",
    "scale": ""
  },
  {
    "id": 30,
    "name": "simulation",
    "description": "it's supposed to simulate a spiecies, that populates itself, and mutates. but 99/100 times it instantly dies. it only shows numbers > the number of entities.",
    "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/simulation/simulation.py",
    "status": "",
    "version": "",
    "type": "Python",
    "tumbnail": "assets/images/appTextures/simulation.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 31,
    "name": "prison Minecraft",
    "description": "A minecraft prison map where you can roleplay and try to escape the prison",
    "link": "",
    "status": "Lost / Cancelled",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/prisonBleuprint.png",
    "creators": "OldMartijntje, Tomsom999",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 32,
    "name": "AI learning (not so great)",
    "description": "An AI that learns to play catch the apple. (yeah succes waiting years for it to do 10 cycles)",
    "link": "https://scratch.mit.edu/projects/552602179/",
    "status": "Cancelled",
    "version": "Beta 1.0",
    "type": "Scratch",
    "tumbnail": "assets/images/appTextures/aiLearning.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 33,
    "name": "Computer OS",
    "description": "Me thinking: yes let's make a Operating system in scratch, it's trash",
    "link": "https://scratch.mit.edu/projects/434035155/",
    "status": "Cancelled",
    "version": "",
    "type": "Scratch",
    "tumbnail": "assets/images/appTextures/os.png",
    "creators": "OldMartijntje",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 34,
    "name": "food clicker",
    "description": "You know about cookie clicker, but have you heard of food clicker??",
    "link": "https://scratch.mit.edu/projects/158671765/",
    "status": "Perfection",
    "version": "0.7.0",
    "type": "Scratch",
    "tumbnail": "assets/images/appTextures/foodClicker.png",
    "creators": "OldMartijntje AKA lollertroller2005",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": ""
  },
  {
    "id": 35,
    "name": "Minecraft Prison",
    "description": "Creating an Minecraft prison where you can play. You can be a guard or warden or prisoner.",
    "link": "henkisjemoederniet.aternos.me",
    "status": "10%?",
    "version": "",
    "type": "Minecraft",
    "tumbnail": "assets/images/appTextures/prison.png",
    "creators": "OldMartijntje, Jake18_Dark, Bartjebro, Mielesgames",
    "readmeUrl": "",
    "userFriendlyness": "",
    "customizebility": "",
    "scale": "C"
  }
];

