import { Project } from 'src/app/models/project';

export const projects: Project[] = [
    {
        "id": 0,
        "name": "UNO",
        "description": "A recreation of UNO using Python. There are multiple versions of the game.\nThere is a version where you can only use console, but it's more advanced, there are a lot of things to change. There is aversion that has a GUI and is less advanced when you are playing, but more advanced when creating uno cards. \nThere are 2 new versions in development.\n1.An UNO api, which you can use in your own code.\n2.A discord bot that uses the UNO api.\nThat's why they are both in development at the same time.",
        "link": "https://github.com/oldmartijntje/UNO",
        "status": "Completed",
        "version": "2.4.0",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/uno.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://github.com/oldmartijntje/UNO/blob/main/README.md",
        "userFriendlyness": "user friendly unless you try to implement your own things, then it's not user friendly.",
        "customizebility": "You add your own cards, you can say how many you want, you can define every card as in: are they special like a + card or a reverse etc.",
        "scale": "B"
    },
    {
        "id": 1,
        "name": "Pokemon Vibranium",
        "description": "This is a pokemon game made by OldMartijntje using rpg maker xp and using pokemon essentials, It takes place in a new region. It has a massive storyline, but to find out what it's about, you should play it yourself. It has an child friendly mode which you can enable / disable when starting a game. When you disable it it will have a dark undertone",
        "link": "https://github.com/oldmartijntje/Pokemon-Vibranium",
        "status": "On Hold",
        "version": "before beta",
        "type": "rpg maker xp + Pokemon Essentials",
        "tumbnail": "assets/images/appTextures/pokemonVibranium.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "fully user friendly.",
        "customizebility": "It's not customizable since it's a pokemon game.",
        "scale": "A"
    },
    {
        "id": 2,
        "name": "Project viewer",
        "description": "An angular web-app with sql server to load all my projects, it also works without the sql server",
        "link": "https://github.com/oldmartijntje/Project-Viewer",
        "status": "On Hold",
        "version": "",
        "type": "Angular, C#",
        "tumbnail": "assets/images/appTextures/viewer.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": "C"
    },
    {
        "id": 3,
        "name": "Accounts System",
        "description": "A Python account system that saves accounts to json, with the account system you can read data from other apps that use this account system, and your playtime gets stored",
        "link": "https://github.com/oldmartijntje/accounts-system",
        "status": "Completed | Upgradable",
        "version": "v2.8.0",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/account.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://github.com/oldmartijntje/accounts-system/blob/main/README.md",
        "userFriendlyness": "client friendly if implemented correctly. It's not that difficult to implement as described in the readme and examples folder.",
        "customizebility": "You can intergrate it in multiple ways, as explained in the readme as well as in the examples folder.",
        "scale": "B"
    },
    {
        "id": 4,
        "name": "stonks",
        "description": "a 'game' where you buy stocks, sell them, and hope you don't go bankrupt. only console, sometimes it's really scuffed.",
        "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/simulation/stonks.py",
        "status": "Completed",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/stonks.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "user friendly, it's explained well",
        "customizebility": "",
        "scale": "D"
    },
    {
        "id": 5,
        "name": "CodeDungeon",
        "description": "This Project is there as learning tool, a tool to teach kids the logic of programming in a fun way, By programming the movement of your character in a game. It requires python 3.10.1+. This game is a dungeon crawler game, inspider by pixeldungeon (and yes with stolen assets). You wake up in a creepy old dungoen with nothing but your sword, so you go find an exit and grab loot along the way, but there are also enemys, to what floor can you get before you die the inevitable death?",
        "link": "https://github.com/oldmartijntje/CodeDungeon",
        "status": "Completed",
        "version": "v1.2.2",
        "type": "Python 3.10.1+",
        "tumbnail": "assets/images/appTextures/codeDungeon.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://github.com/oldmartijntje/CodeDungeon/blob/main/README.md",
        "userFriendlyness": "very user friendly, there is a massive readme that explains everything. And even if you don't want to read, just run the installer, run the example.py and see where you can get. (and maybe in the future there is a version where you don't have to program the inputs, where you can just play, or maybe you make it yourself?",
        "customizebility": "You can change almost everything, add almost everything, very customizable. everything is explained in my readme.",
        "scale": "S"
    },
    {
        "id": 6,
        "name": "LAN-testing",
        "description": "Me testing how lan works, i was going to implement it into uno, but not yet. It's a LAN chat, console version and Tkinter version.",
        "link": "https://github.com/oldmartijntje/LAN-testing",
        "status": "Completed",
        "version": "V0.3.0",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/lan.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "pretty straight forward. Unless you don't know what an IP adress is.",
        "customizebility": "I mean you can implement it in a lot, if you know a bit of coding.",
        "scale": "C"
    },
    {
        "id": 7,
        "name": "pokemarjin",
        "description": "i was going to make a Pokemon game.",
        "link": "https://github.com/oldmartijntje/pokemarjin",
        "status": "Cancelled",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/pokemarjin.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 8,
        "name": "Betacraft",
        "description": "Minecraft world using the betacraft launcher where i update the world every time i open the world",
        "link": "https://betacraft.uk/",
        "status": "On Hold",
        "version": "b1.7.3",
        "type": "BetaCraft Minecraft",
        "tumbnail": "assets/images/appTextures/betacraft.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://youtu.be/LAXe4MJEs-o",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": "B"
    },
    {
        "id": 9,
        "name": "Reliving -The game",
        "description": "This is a story game i guess, you get options about what to do and you can choose, can you find all the achievements? if you have a file named DLC.activ in the main folder (doesn't matter if it contains data) (you can find one in the DLC/ folder) You have an extra branch to the game, with more achievements, but it's not finished.",
        "link": "https://github.com/oldmartijntje/The-Game",
        "status": "DLC: Cancelled | Original game: Completed",
        "version": "Release 3.2",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/reliving.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://github.com/oldmartijntje/The-Game/blob/master/README.md",
        "userFriendlyness": "Pretty self explanetory, and the readme helps",
        "customizebility": "some settings in the readme",
        "scale": "D"
    },
    {
        "id": 10,
        "name": "Isis's idee.nds",
        "description": "A mario bros ds hack where i got ideas for levels from my friend. every level started from a hub where 1 diff pipe is opened to start the level.",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/isisIdee.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 11,
        "name": "texturepackremovalform",
        "description": "Ever had a texture pack u liked in minecraft, but u hated that 1 texture? exactly, i did. so i made this, now you only need to fill in in a txt which textures u hate, and every time when it updates, you can delete those annoying textures. (if it still works) (you need all the files in that folder in the link, but not the whole reposetory) once u downloaded it, head to: texturepackremovalform/bin/Debug/net5.0-windows/texturepackremovalform.exe to activate it.",
        "link": "https://github.com/oldmartijntje/projects/tree/main/csharp/repos/texturepackremovalform",
        "status": "Completed",
        "version": "V1.4",
        "type": "C#",
        "tumbnail": "assets/images/appTextures/texturepackremoval.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "Yeah it's explained quite well, i think?",
        "customizebility": "",
        "scale": "OG"
    },
    {
        "id": 13,
        "name": "City Build",
        "description": "It's a city in minecraft, well atleast the start",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/cityBuild.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 16,
        "name": "Hard Shit.nds",
        "description": "A kaizo mario bros ds hack which is only one level",
        "link": "",
        "status": "Completed",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/hardShit.png",
        "creators": "Someone on discord",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 18,
        "name": "nakijk formulier",
        "description": "This is a program that fills in a form that i had to fill in every time for school and i didn't want to do that every time, so i automated it.",
        "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/nakijk%20formulier/nakijk.py",
        "status": "Completed",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/nakijk.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "client friendly, just do what it says",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 19,
        "name": "phone",
        "description": "a random calculator that just says you are 10% dumb or something which is randomized. the reason why it's called phone is because i probably made it on my phone.",
        "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/simulation/phone.py",
        "status": "Completed?",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/phone.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "user friendly, but u only need to fill in a name, that's all",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 20,
        "name": "Golf",
        "description": "Golf coarse in minecraft",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/golf.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 21,
        "name": "Broken Realms",
        "description": "A minecraft server",
        "link": "",
        "status": "Cancelled (forever)",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/brokenRealms.png",
        "creators": "OldMartijntje, Tomsom999, MellodieMoon, Dejack13",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 22,
        "name": "Minecraft Town",
        "description": "A town in Minecraft where you can play, and with lore.",
        "link": "",
        "status": "Not even started and already Cancelled",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/minecraftTown.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 23,
        "name": "Animation maker",
        "description": "An animation maker",
        "link": "https://scratch.mit.edu/projects/436600255/",
        "status": "Cancelled",
        "version": "",
        "type": "Scratch",
        "tumbnail": "assets/images/appTextures/animationMaker.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 24,
        "name": "good.nds",
        "description": "An 'openworld' mario bros ds hack where every level starts where the last one ended",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/good.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 25,
        "name": "official nsmb, but switchable tilesets.nds",
        "description": "A new super mario bros ds hack with the original levels, but the tilesets match so it's easy to switch enviroment",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/tileset.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 26,
        "name": "Project.nds",
        "description": "A mod where different world are meant for different types of people",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/project.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 27,
        "name": "test.nds",
        "description": "Me testing if you can do a shelljump in new super mario bros ds with a edited level to test it",
        "link": "",
        "status": "Completed",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/test.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 28,
        "name": "watar.nds",
        "description": "I flooded every mario bros ds level, unless it's a water level, then i drained it",
        "link": "",
        "status": "Completed",
        "version": "",
        "type": "NSMB Editor",
        "tumbnail": "assets/images/appTextures/watar.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 29,
        "name": "book",
        "description": "this program generates a give command for minecraft with a randomized story. you can add more things (sentances and stuff) in the json file. how 2 add + how it works: it takes 1 string from the intros dictionary, once it encounters a word with || around it, like this: ||item|| it will take a string from the items dictionary and it will reread the string, until it doesn't encounter a word with || around it anymore. (same thing works with author and name, tho those can't contain spaces, be aware) as title it will pick from ||titles|| and as author it will pick from ||authors|| (authors doesn't exist in the json, it is generated once the script is running by merging some ||people|| with ||newspaper||)",
        "link": "https://github.com/oldmartijntje/projects/blob/main/minecraft/book.py",
        "status": "Completed",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/book.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "You can add as many words and centances as you wish",
        "scale": ""
    },
    {
        "id": 30,
        "name": "simulation",
        "description": "it's supposed to simulate a spiecies, that populates itself, and mutates. but 99/100 times it instantly dies. it only shows numbers > the number of entities.",
        "link": "https://github.com/oldmartijntje/projects/blob/main/smol%20projects/simulation/simulation.py",
        "status": "Completed",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/simulation.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 31,
        "name": "prison Minecraft",
        "description": "A minecraft prison map where you can roleplay and try to escape the prison",
        "link": "",
        "status": "Lost / Cancelled",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/prisonBleuprint.png",
        "creators": "OldMartijntje, Tomsom999",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 32,
        "name": "AI learning (not so great)",
        "description": "An AI that learns to play catch the apple. (yeah succes waiting years for it to do 10 cycles)",
        "link": "https://scratch.mit.edu/projects/552602179/",
        "status": "Cancelled",
        "version": "Beta 1.0",
        "type": "Scratch",
        "tumbnail": "assets/images/appTextures/aiLearning.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 33,
        "name": "Computer OS",
        "description": "Me thinking: yes let's make a Operating system in scratch, it's trash",
        "link": "https://scratch.mit.edu/projects/434035155/",
        "status": "Cancelled",
        "version": "",
        "type": "Scratch",
        "tumbnail": "assets/images/appTextures/os.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 34,
        "name": "food clicker",
        "description": "You know about cookie clicker, but have you heard of food clicker??",
        "link": "https://scratch.mit.edu/projects/158671765/",
        "status": "Completed",
        "version": "0.7.0",
        "type": "Scratch",
        "tumbnail": "assets/images/appTextures/foodClicker.png",
        "creators": "OldMartijntje AKA lollertroller2005",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 35,
        "name": "Minecraft Prison",
        "description": "Creating an Minecraft prison where you can play. You can be a guard or warden or prisoner. It has enough place to maybe build a city or something. It's in my creative testworld so the worldfiles are alreade 1 and a half gigabyte.",
        "link": "https://www.youtube.com/watch?v=ROAejCjnwLU&feature=youtu.be",
        "status": "Cancelled",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/prison.png",
        "creators": "OldMartijntje, Jake18_Dark, Bartjebro, Mielesgames",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": "C"
    },
    {
        "id": 36,
        "name": "Rotate an 2D Array",
        "description": "This project rotates a 2D array, and if you want to rotate a 3D array, just split the 3D array into 2D slices and then run the function and then merge it back into a 3D array. Or even simpler, put in the 3D erray and it will work too, but it can rotate only in 1 way then. Gonna use this as extra tool for my CodeDungoen project.",
        "link": "https://github.com/oldmartijntje/projects/blob/main/rotateArray.py",
        "status": "Completed",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/rotateArray.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "user friendly, It's just a function, you put in an array and an int as arguments, and it rotates the erray 90 degrres times the intager you also gave as input.",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 37,
        "name": "Game Database",
        "description": "This is a Database with i think all games, it uses an api to grab the games, it has some nice search options, and about page and other fun features, this was made using a tutorial mostly, but i added a lot of custom things myself. the tuturial is linked in the about page in the project itself",
        "link": "https://github.com/oldmartijntje/internship/tree/master/angular-test/Game-Database",
        "status": "Completed",
        "version": "",
        "type": "Angular",
        "tumbnail": "assets/images/appTextures/gameDatabase.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "user friendly, just search for a game, apply some filters, or click the random game button. Scroll down to see settings.",
        "customizebility": "You can change the app color theme, though the themes aren't the best design wise",
        "scale": "E"
    },
    {
        "id": 38,
        "name": "Map Viewer - Openlayers Angular",
        "description": "This is a map viewer made in angular, click on the map to see a location, double click to set a marker, that can't be removed. It is meant to later show all locations from my internship their api, but right now we have problems with that.",
        "link": "https://github.com/oldmartijntje/internship/tree/master/angular-test/openlayers-angular",
        "status": "Completed",
        "version": "",
        "type": "Angular",
        "tumbnail": "assets/images/appTextures/map.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 39,
        "name": "SafetyCT - TrainingsModule",
        "description": "The rebuilding of the SafetyCT testing module, that later gets turned into the DCU app",
        "link": "",
        "status": "In Progress",
        "version": "",
        "type": "Angular",
        "tumbnail": "assets/images/appTextures/training.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 40,
        "name": "Pokemon Backrooms",
        "description": "When you suddenly no-clip into the backrooms in a Pokemon game",
        "link": "https://github.com/oldmartijntje/Pokemon-Backrooms",
        "status": "Completed",
        "version": "v1",
        "type": "rpg maker xp + Pokemon Essentials",
        "tumbnail": "assets/images/appTextures/pokemon-backrooms.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://youtu.be/4F9SEL7j_CY",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": "E"
    },
    {
        "id": 41,
        "name": "LAN Game",
        "description": "A game that uses and utilizes my LAN and Accounts system",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 42,
        "name": "Account viewer",
        "description": "An app that is uses to look into your account from my account system",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "Angular",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 43,
        "name": "JSON changer",
        "description": "A python app that 1 by 1 loads an item from a json, and you can copy and edit the item, it is made to make translations easy.",
        "link": "https://github.com/oldmartijntje/projects/blob/main/jsonEditor.py",
        "status": "Completed",
        "version": "V1",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/jsonEditor.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 44,
        "name": "Create samples",
        "description": "a program that creates samples of a json",
        "link": "https://github.com/oldmartijntje/projects/blob/main/createSamples.py",
        "status": "Completed",
        "version": "V1",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/sampler.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 45,
        "name": "Genetica",
        "description": "A game inspired by marvel Snap. You battle with cards, and to unlock new ards you merge them.",
        "link": "",
        "status": "Cancelled",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 46,
        "name": "Discord UNO",
        "description": "A recreation of UNO, But than as discord bot. It's in the same reposetory as normal UNO, but not the same py",
        "link": "https://github.com/oldmartijntje/UNO",
        "status": "On Hold",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://github.com/oldmartijntje/UNO/blob/main/README.md",
        "userFriendlyness": "",
        "customizebility": "Whatever the api can do probably.",
        "scale": ""
    },
    {
        "id": 47,
        "name": "UNO api",
        "description": "A recreation of UNO, But it's an api, which the bot uses to run the game. It's in the same reposetory as normal UNO, but not the same py",
        "link": "https://github.com/oldmartijntje/UNO",
        "status": "On Hold",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "https://github.com/oldmartijntje/UNO/blob/main/README.md",
        "userFriendlyness": "",
        "customizebility": "Right now you can change how every bot thinks.",
        "scale": ""
    },
    {
        "id": 48,
        "name": "AdvancePad",
        "description": "A library where you can put any text, filter on it, lock it, have intergrated code boxes, editor built in.",
        "link": "https://github.com/oldmartijntje/Advancepad",
        "status": "On Hold",
        "version": "",
        "type": "Python",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    },
    {
        "id": 49,
        "name": "Adventure Map",
        "description": "A minecraft adventure map using immersive portals and create mod.",
        "link": "",
        "status": "In Progress",
        "version": "",
        "type": "Minecraft",
        "tumbnail": "assets/images/appTextures/textureMissing.png",
        "creators": "OldMartijntje",
        "readmeUrl": "",
        "userFriendlyness": "",
        "customizebility": "",
        "scale": ""
    }
];

